server:
  port: 8080
  web:
    allowed-origins:  http://localhost:4200/, http://localhost:5000/

spring:
  datasource:
    url: jdbc:sqlserver://gocasego.database.windows.net:1433;database=equipatour;user=adminquipa@gocasego;password=23#as#Apsd.10;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

# swagger-ui custom path
springdoc:
  swagger-ui.path: '/swagger-ui.html'
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    operations-sorter: none
  server:
    url: http://localhost:8080

# Hibernate SQL Logging
logging:
  level:
    root: INFO
    org.hibernate:
      sql: WARN
      type: WARN
debug: true